name: Check PR

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: 'Run lint'
    uses: ./.github/workflows/run-lint.yml
  tests:
    name: 'Run tests'
    uses: ./.github/workflows/run-tests.yml
  build:
    name: 'Run tsc'
    uses: ./.github/workflows/run-tsc.yml
