name: Run tests

on:
  workflow_call

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run unit tests with coverage
        run: yarn coverage
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: coverage/unit
          path: coverage

  e2e:
    strategy:
      matrix:
        browser: [chrome, firefox]
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:latest
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Run cypress e2e testing
        uses: cypress-io/github-action@v5
        with:
          browser: ${{ matrix.browser }}
          start: yarn d --listen 5137
          wait-on: 'http://localhost:5137'
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: coverage/e2e
          path: coverage
